######################################################################
# Automatically generated by qmake (2.01a) ?? 8. ??? 08:21:24 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
