######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 21 17:10:49 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
